---

- name: Ensure path exists and has correct ownership
  file:
    path: "{{ item.path | dirname }}"
    state: "directory"
    owner: "{{ nexus_os_user }}"
    group: "{{ nexus_os_group }}"

- include: call_script.yml
  vars:
    script_name: create_blobstore
    args: "{{ item }}"
