---

- name: Copy httpd vhost
  template:
    src: "nexus-vhost.conf"
    dest: "/etc/httpd/conf.d"

- name: Copy SSL certificate file
  copy:
    src: "{{ httpd_ssl_certificate_file }}"
    dest: "/etc/pki/tls/certs"
    mode: 0600

- name: Copy SSL certificate key file
  copy:
    src: "{{ httpd_ssl_certificate_key_file }}"
    dest: "/etc/pki/tls/private"
    mode: 0600

- name: Copy SSL certificate chain file
  copy:
    src: "{{ httpd_ssl_certificate_chain_file }}"
    dest: "/etc/pki/tls/certs"
    mode: 0600

- name: Set se linux boolean thing
  seboolean:
    name: httpd_can_network_connect
    state: yes
    persistent: yes

- name: Restart httpd
  systemd:
    state: restarted
    daemon_reload: yes
    name: httpd

- name: Waiting for httpd to be restarted
  wait_for:
    port: 443
    delay: 5
